### ISSUE TITLE
Constructor : is CI required?

### ISSUE THREAD

**Issue by yahyaerturan** [davinder17s/codeigniter-middleware#1]
Hi,

Thanks for great work. I was looking for a middleware for a long time.

One question:

`$this->controller` seems already as an instance. We can even do like `$this->controller->db->get('users')`. I want to ask is there a special reason to add `$ci` in constructor. I am not sure but it feels like a duplicate of `$controller` - however I am not an expert.

**Comment by davinder17s** [comment]
No its not required, its just to have references when you need

**Comment by davinder17s** [comment]
Fixes #1
